/*
 * OpenAlex
 *
 * OpenAlex APIs
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Concept struct {
	Ancestors []AncestorConcept `json:"ancestors,omitempty"`
	// number of times papers with this tag have been cited
	CitationCount int32 `json:"citation_count,omitempty"`
	CreatedDate string `json:"created_date,omitempty"`
	// full name of the journal
	DisplayName string `json:"display_name,omitempty"`
	MainType string `json:"main_type,omitempty"`
	// number of papers associated with this concept
	PaperCount int32 `json:"paper_count,omitempty"`
}
