/*
 * OpenAlex
 *
 * OpenAlex APIs
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Work struct {
	AbstractInvertedIndex *AbstractInvertedIndex `json:"abstract_inverted_index,omitempty"`
	Affiliations []Affiliation `json:"affiliations,omitempty"`
	// Host type
	BestHostType string `json:"best_host_type,omitempty"`
	BestLicense string `json:"best_license,omitempty"`
	BestUrl string `json:"best_url,omitempty"`
	// Version of the paper
	BestVersion string `json:"best_version,omitempty"`
	// number of times this paper has been cited
	CitationCount int32 `json:"citation_count,omitempty"`
	Citations []WorkExtraIds `json:"citations,omitempty"`
	// concepts
	Concepts []Concept `json:"concepts,omitempty"`
	CreatedDate string `json:"created_date,omitempty"`
	// doc_type
	DocType string `json:"doc_type,omitempty"`
	FirstPage string `json:"first_page,omitempty"`
	// genre
	Genre string `json:"genre,omitempty"`
	Ids *WorkExtraIds `json:"ids,omitempty"`
	Issue string `json:"issue,omitempty"`
	Journal *Journal `json:"journal,omitempty"`
	LastPage string `json:"last_page,omitempty"`
	Locations []Location `json:"locations,omitempty"`
	Mesh []Mesh `json:"mesh,omitempty"`
	// Open Access status of the paper
	OaStatus string `json:"oa_status,omitempty"`
	// title of the paper
	PaperTitle string `json:"paper_title,omitempty"`
	// date of publication
	PublicationDate string `json:"publication_date,omitempty"`
	Volume string `json:"volume,omitempty"`
	// year of publication
	Year int32 `json:"year,omitempty"`
}
