/*
 * OpenAlex
 *
 * OpenAlex APIs
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Affiliation struct {
	Author *Author `json:"author,omitempty"`
	// author order
	AuthorSequenceNumber int32 `json:"author_sequence_number,omitempty"`
	Institution *InstitutionSmall `json:"institution,omitempty"`
}
