/*
 * OpenAlex
 *
 * OpenAlex APIs
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InstitutionSmall struct {
	OriginalAffiliation string `json:"original_affiliation,omitempty"`
}
