/*
 * OpenAlex
 *
 * OpenAlex APIs
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Journal struct {
	// number of times this author has been cited
	CitationCount int32 `json:"citation_count,omitempty"`
	CreatedDate string `json:"created_date,omitempty"`
	// full name of the journal
	DisplayName string `json:"display_name,omitempty"`
	IsInDoaj bool `json:"is_in_doaj,omitempty"`
	IsOa bool `json:"is_oa,omitempty"`
	// linking ISSN for this journal
	IssnL string `json:"issn_l,omitempty"`
	// all ISSNs for this journal, print and electronic
	Issns []string `json:"issns,omitempty"`
	// number of papers this author has published
	PaperCount int32 `json:"paper_count,omitempty"`
	Publisher string `json:"publisher,omitempty"`
	UpdatedDate string `json:"updated_date,omitempty"`
}
