/*
 * OpenAlex
 *
 * OpenAlex APIs
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WorkExtraIds struct {
	Doi string `json:"doi,omitempty"`
	DoiUrl string `json:"doi_url,omitempty"`
	Pmid string `json:"pmid,omitempty"`
	PmidUrl string `json:"pmid_url,omitempty"`
}
