/*
 * OpenAlex
 *
 * OpenAlex APIs
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Mesh struct {
	DescriptorName string `json:"descriptor_name,omitempty"`
	DescriptorUi string `json:"descriptor_ui,omitempty"`
	QualifierName string `json:"qualifier_name,omitempty"`
	QualifierUi string `json:"qualifier_ui,omitempty"`
}
