/*
 * OpenAlex
 *
 * OpenAlex APIs
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Author struct {
	AllInstitutions []InstitutionSmall `json:"all_institutions,omitempty"`
	// number of times this author has been cited
	CitationCount int32 `json:"citation_count,omitempty"`
	CreatedDate string `json:"created_date,omitempty"`
	// full name of the author
	DisplayName string `json:"display_name,omitempty"`
	LastKnownInstitution *Institution `json:"last_known_institution,omitempty"`
	Orcid string `json:"orcid,omitempty"`
	OrcidUrl string `json:"orcid_url,omitempty"`
	// number of papers this author has published
	PaperCount int32 `json:"paper_count,omitempty"`
	UpdatedDate string `json:"updated_date,omitempty"`
}
