/*
 * OpenAlex
 *
 * OpenAlex APIs
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Institution struct {
	// city of institution
	City string `json:"city,omitempty"`
	// name of country
	Country string `json:"country,omitempty"`
	// 2-character country code
	CountryCode string `json:"country_code,omitempty"`
	CreatedDate string `json:"created_date,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	// GRID id (deprecated in favour of ROR id)
	GridId string `json:"grid_id,omitempty"`
	// url of institution
	OfficialUrl string `json:"official_url,omitempty"`
	RorId string `json:"ror_id,omitempty"`
	RorUrl string `json:"ror_url,omitempty"`
	// url of Wikipedia page of institution
	WikipediaUrl string `json:"wikipedia_url,omitempty"`
}
