/*
 * OpenAlex
 *
 * OpenAlex APIs
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Location struct {
	// Host type
	HostType string `json:"host_type,omitempty"`
	LanguageCode string `json:"language_code,omitempty"`
	License string `json:"license,omitempty"`
	OaiPmhId string `json:"oai_pmh_id,omitempty"`
	RepositoryInstitution string `json:"repository_institution,omitempty"`
	// Type of resource at the Source URL
	SourceDescription string `json:"source_description,omitempty"`
	SourceType int32 `json:"source_type,omitempty"`
	SourceUrl string `json:"source_url,omitempty"`
	UrlForLandingPage string `json:"url_for_landing_page,omitempty"`
	UrlForPdf string `json:"url_for_pdf,omitempty"`
	// Version of the paper
	Version string `json:"version,omitempty"`
}
